[package]
name = "kwaak"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.88"
crossterm = "0.28.1"
ratatui = "0.28.1"
tokio = { version = "1.40.0", features = ["full"] }
strum = "0.26.3"
strum_macros = "0.26.4"
swiftide = { version = "0.13.0", features = [
  "lancedb",
  "openai",
  "tree-sitter",
] }
toml = "0.8.19"
serde = { version = "1.0.210", features = ["derive"] }
secrecy = { version = "0.10.2", features = ["serde"] }
tracing = "0.1.40"
async-openai = "0.24.1"

[workspace.lints.rust]
unsafe_code = "forbid"
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(coverage,coverage_nightly)',
] }

[workspace.lints.clippy]
cargo = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
blocks_in_conditions = "allow"
must_use_candidate = "allow"
module_name_repetitions = "allow"
missing_fields_in_debug = "allow"
# Should be fixed asap
multiple_crate_versions = "allow"
