language = "rust"
tool_executor = "local"

[github]
owner = "bosun-ai"
repository = "kwaak"
main_branch = "master"

[commands]
test = "npm test -- --coverage --watchAll=false --bail=1 -u --coverageReporters=cobertura 2>/tmp/coverage_tool.log 1>/tmp/coverage_tool_output.log && cat coverage/cobertura-coverage.xml"
coverage = "npm test -- --coverage --watchAll=false --bail=1 -u --coverageReporters=cobertura 2>/tmp/coverage_tool.log 1>/tmp/coverage_tool_output.log && cat coverage/cobertura-coverage.xml"

[llm.indexing]
api_key = "env:OPENAI_API_KEY"
provider = "OpenAI"
prompt_model = "gpt-4o-mini"
base_url = "https://api.openai.com/v1"

[llm.query]
api_key = "env:OPENAI_API_KEY"
provider = "OpenAI"
prompt_model = "gpt-4o"
base_url = "https://api.openai.com/v1"

[llm.embedding]
api_key = "env:OPENAI_API_KEY"
provider = "OpenAI"
embedding_model = "text-embedding-3-large"
base_url = "https://api.openai.com/v1"
